# This is a basic workflow to help you get started with Actions
name: aux

on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
              python-version: '3.9'
              cache: 'pip' # caching pip dependencies
      - name: install python packages
        run:
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute python script
        env:
          ACCOUNT_KEY: ${{ secrets.ACCOUNT_KEY }}
        run: python aux_deputados.ipynb 
